import "./globals.css";
import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import { Poly, Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"],
weight : ['400','700','500'],
// variable: '--font-poppins',
variable: ''
}); 

const poly = Poly({ subsets: ["latin"],
weight : ['400'],
variable: '--font-poly'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.className}   ${poly.className} `}>
        <Header/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
